places = ['Colorado','Chicago','Quebec','Toronto','Portland']
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
print(sorted(places))
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)